app:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 30
    jdbc-url: jdbc:postgresql://localhost:5432/atc_db
    username: postgres
   # username: ENC(Qo4oTu4zcLcxWWnKKYmWrXFwmO18jMFX)
    password: password
   # password: ENC(NyvURBzbkIGeiEiWaOLVLfBgz8v3I+DU)
    max-pool-size: 30


